### ISSUE TITLE
parser rejects quantified subexpression

### ISSUE THREAD

**Issue by danielgrahl** [janhaag/PSE2011#12]
An expression like the following is rejected by the parser ("no viable alternative at input 'forall'"). I tried to put in as much parentheses as possible, but it still fails.
(0 < i) & ((i <= length(a)) & (forall j (0,i-1) (x >= a[j])));

**Comment by janhaag** [comment]
Currently, quantification over subexpressions is not allowed. The following expression should be equivalent and parse correctly:

forall j (0, i - 1) 0 < i & (i <= length(a) & x >= a[j])

I'm closing this issue for now.

**Comment by ratefuchs** [comment]
please mind that "&" binds stronger than "<=", ">=", and "<" so you need to put in some more parentheses in order that this expression is type correct:

forall j (0, i - 1) (0 < i) & ((i <= length(a)) & (x >= a[j]))
