### ISSUE TITLE
possible division by zero in quantified expression

### ISSUE THREAD

**Issue by danielgrahl** [janhaag/PSE2011#15]
Parsing the following program fails, because the parser tries to put an "assert x != 0" in front of it, but x is not declared.
main (){} ensure forall x() 1/x == 1;

**Comment by janhaag** [comment]
Currently, the parser pushes these assertions up the call stack. This leads to the described behavior. The quick fix seems to be to push everything down the call stack. This definitely will cause problems once we allow for quantification over subexpressions, though, and I'm not entirely sure it doesn't cause problems now.

**Comment by janhaag** [comment]
I've implemented the quick fix above, it should work now (i. e. the ensure fails).
