### ISSUE TITLE
incorrect behavior of load and save 

### ISSUE THREAD

**Issue by linjin** [janhaag/PSE2011#23]
problems with loading/saving to files which are no text files

**Comment by tschlum** [comment]
There is no way to tell binary files from text files, and there is no file extension associated with source files yet, so saving into or loading from binary files is not prohibited in any way.

**Comment by linjin** [comment]
we should limit the files for load/save to txt files and files created by our program

**Comment by tschlum** [comment]
Only files ending in ".wp" or ".txt" are loaded and saved as of 17b467c894182bc003d4c36c2c61b26987715853.
