### ISSUE TITLE
Memory limit and timeout settings are not passed to Z3

### ISSUE THREAD

**Issue by syras** [janhaag/PSE2011#31]
The memory limit and timeout settings are not passed to Z3, so a change in these settings has no effect on the behavior of the verifier.

**Comment by syras** [comment]
Passing the settings with the following syntax results in an IOException:
"/T:$timeout /memory:$memory $path ${FILE} -m"
@janhaag please take a look at this...

**Comment by janhaag** [comment]
I added MEMORY_LIMIT and TIMEOUT to the supported variables.
EDIT: Remember that the syntax for variables is ${VARIABLE}...

**Comment by tschlum** [comment]
Z3 requires parameters to be seperated by colons (':'), not whitespace.
