### ISSUE TITLE
[Feature Request] "Delete"-Button for global breakpoints

### ISSUE THREAD

**Issue by syras** [janhaag/PSE2011#38]
If you want to delete a global breakpoint you have to manually copy the whole statement (which wastes a lot of time - especially with large statements). There should be a possibility to delete a single global breakpoint with 1-2 mouse clicks (e.g. a delete button in every row of the table).

**Comment by ratefuchs** [comment]
A global breakpoint is deleted if the same breakpoint is added again. So I think it would probably be enough to put the respective breakpoint in the text field if it is double-clicked (also a good way to change them).

**Comment by linjin** [comment]
This feature is added in de399f76fa98fdf62537ca003ace3aff8bb5fade. The clicked expression is copied to the textfield
