### ISSUE TITLE
illegal statement written at help topic "Functions"

### ISSUE THREAD

**Issue by ratefuchs** [janhaag/PSE2011#50]
In the help topic "Functions", section "Function Call", the example at the bottom is:

f(x+3);

This is neither a statement (no assignment or declaration) nor a valid expression (due to the ";").
It would be better if only the function call expression is used.

**Comment by tschlum** [comment]
Fixed in 8503186cd1a762306dd8453466fbe9c57d67078a.
The example now contains only the function call expression.
