### ISSUE TITLE
Arrays as special case forgotten in "Assignment" help topic

### ISSUE THREAD

**Issue by ratefuchs** [janhaag/PSE2011#52]
It is not mentioned that on an array assignment there are implicit checks of whether array indices are within the allowed range
             (0 <= index < length)
and its implication on single step mode (stopping multiple times).

Additionally, it has to be mentioned that one must not assign a value to a non-complete indexed array (i.e. if "a" is a 2D array, one may neither assign something to "a" or "a[0]", only assignments to "a[index1][index2]" are allowed).

**Comment by tschlum** [comment]
Fixed in 3e3393bc6dcb35600ed67f8eca79073b92d6c3ac.

**Comment by tschlum** [comment]
The syntax of array assignments is not correct.

**Comment by tschlum** [comment]
Fixed in fbb5f80b351402c0ac69b8778ff4ab696c31f325.
