### ISSUE TITLE
Article mentioned in "While-Statement" help not present

### ISSUE THREAD

**Issue by ratefuchs** [janhaag/PSE2011#53]
In the "While-Statement" help article there is a reference to an article "assertions", which does not exist.
Only a (non-relevant) article named "Assert" exists.
There should be a reference to "Invariant" and "Ensure" instead, or probably a new article "Specification", where a general description is given and where all types of specifications are enumerated.

**Comment by tschlum** [comment]
Fixed in 57cb49f9c3fb76b3568f55b5c01509eaa0836e0f.
