### ISSUE TITLE
Verification has false-positives and false-negatives

### ISSUE THREAD

**Issue by danielgrahl** [janhaag/PSE2011#6]
There are several proof obligations generated, but it is unclear which ones a program must fulfill in order to be deemed correct. Take the following program for instance:
main(){ int x; int y; while (y == 0){ x = x+1; } } ensure x >0;
It obviously fulfills its postcondition. Yet this should not be provable without an invariant. 
However, the proof obligation "InvariantAndNotConditionToEnsure" says "true" (false-negative).
There is another proof obligation "WhileEnsureToRemaining" that reports "false" even in case there is an invariant given (false-positive).

**Comment by danielgrahl** [comment]
Maybe it's still correct this way, but the different proof obligatins are confusion.

**Comment by ratefuchs** [comment]
I don't see any problems (maybe there are, but this cannot be seen in this description).
It rather seems that the different obligation annotations are unclear, which is a missing documentation problem.
The documentation part is replaced by issue #63.

I will close the topic for now.
