### ISSUE TITLE
description of "/" and "%" wrong

### ISSUE THREAD

**Issue by ratefuchs** [janhaag/PSE2011#62]
"/" does not round to zero. It is more complicated as it uses SMTLib definitions; see
http://goedel.cs.uiowa.edu/smtlib/theories/Ints.smt2
for more details (this also affects "%" definition).

"/" and "%" by zero are not needed as we have the implicit checks before those statements; and we don't recover from Specification failure. However, description of the implicit checks should be given.

The interpreter stops one additional time on each "%", not only on "/".

**Comment by tschlum** [comment]
The explanation of these two operators is not detailed enough.

**Comment by tschlum** [comment]
Fixed in a56e35305d117ba6d8020610f3fac9128d538e21.
