### ISSUE TITLE
"Errors" console sometimes not cleared properly

### ISSUE THREAD

**Issue by ratefuchs** [janhaag/PSE2011#65]
When I type the following program:
main(){}
click ckeck syntax, amend the program that it is:
main(){}ensure;
and click check syntax again, I get two messages:

1                      no viable alternative at input 'ensure'
0                      Syntax is correct!

This is strange because the syntax is not correct.

**Comment by tschlum** [comment]
Checking the syntax of the program
main(){}ensure;
without any prior action will still print both messages, so I guess this is due to antlr's error recovery being able to generate an AST successfully.

**Comment by janhaag** [comment]
This shouldn't happen, as this definitely leads to error recovery being triggered. I'll have to look into this, but it may be the Parser just gobbles up the extra 'ensure' token -- or it generates an error token for the missing QuantifiedExpression.

**Comment by ratefuchs** [comment]
Problem already solved (not reproducible in current version).
It was problably fixed together with issue #45 in f2e91c0.
