### ISSUE TITLE
program containing certain variables behave strange

### ISSUE THREAD

**Issue by ratefuchs** [janhaag/PSE2011#67]
When trying to prove the following program:
main(int ite){}ensure ite==1;
no result is given to gui consoles, but my IDE console shows the following error messages:

line 1:0 required (...)+ loop did not match anything at input '('
line 1:45 no viable alternative at character ','

It works fine with variables like "f", "t", or "_ite".
It also fails with "distinct".

Probably there's a conflict with SMTLib functions.

**Comment by janhaag** [comment]
The solution is probably to mangle the name of variables to ensure they don't accidentally end up being interpreted as keywords.

**Comment by ratefuchs** [comment]
Fixed in cd2fe4c.
