### ISSUE TITLE
Quantifier bounds not respected in SMTLibTranslation

### ISSUE THREAD

**Issue by ratefuchs** [janhaag/PSE2011#81]
so "exists x(1,4)" has the same effect as "exists x()".

**Comment by headri** [comment]
forall x (1,1) says line 3:21 required (...)+ loop did not match anything at input ')'
Should I open a new Issue for this?

**Comment by ratefuchs** [comment]
Open a new issue, please, and give a detailed(!) description.

Fixed in 93a9142.
