### ISSUE TITLE
z3 grammar cannot parse all quantified expression results correctly

### ISSUE THREAD

**Issue by ratefuchs** [janhaag/PSE2011#82]
When proving the following program:

main(){}ensure exists x() forall y() x==y;

the confusing result message "false; [1]=1" is shown on verifier console.
IDE console yields an error message:
line 6:19 mismatched input '!' expecting '('

The result given by Z3 is correct SMTLib code:

sat
(model 
  (define-fun k!5 ((x!1 Int)) Int
    (ite (= x!1 1) 1
      0))
  (define-fun y$2!0!6 ((x!1 Int)) Int
    (ite (= x!1 1) 2
      1))
  (define-fun y$2!0 ((x!1 Int)) Int
    (y$2!0!6 (k!5 x!1)))
)

**Comment by headri** [comment]
This is not a only a problem on z3 Grammar. The correct output of z3 should be sat (model()), because for 
"ensure forall x() exists y() x!=y;" z3 says "unsat". Which means it is always correct.
However, I changed the grammar: It accepts now this code.

**Comment by ratefuchs** [comment]
But if you want to disprove "ensure exists x() forall y() x==y", you have to give an y for each x as counterexample (so that x!=y).

**Comment by ratefuchs** [comment]
Error message now doesn't show up.

However, did you output the last function definition?

That would be
(define-fun y$2!0 ((x!1 Int)) Int
(y$2!0!6 (k!5 x!1)))
and is the important function in this model.

**Comment by headri** [comment]
Now I put it out, but output is not correct yet, because it prints y$2 = y$2(k(x)) with two different y$2. And x is even x if you write "main(){}ensure exists y() forall x() x==y;"

**Comment by janhaag** [comment]
The output seems to be correct now, albeit somewhat cryptic on the first glance...
