### ISSUE TITLE
Division in quantifier range is translated wrong

### ISSUE THREAD

**Issue by ratefuchs** [janhaag/PSE2011#83]
When executing the following program:

main(){int z=2;}ensure exists z(0,1/z) true;

the ensure fails. Debugging shows that the parser pushes the "division by zero prevention" into the expression that is quantified (i.e. makes it to "ensure exists z(1,1/z) ((z != 0) & true)"). But that moves the expression into an inner scope and the inner z is taken to evaluate z != 0. But it has to be the outer z.

**Comment by janhaag** [comment]
This issue may be tricky to solve, as we don't allow fully quantified subexpressions. A (very ugly) quick fix would be to allow only literals in ranges.

**Comment by janhaag** [comment]
It seems that quantification over subexpressions does indeed work.
