### ISSUE TITLE
Function call is skipped if it has a function call as parameter

### ISSUE THREAD

**Issue by linjin** [janhaag/PSE2011#84]
When running the following program in single step, you can see that only foo2() is called and foo() not:

int foo(int a) {
    return a + 10;
}

int foo2() {
    return 2;
}

main() {
    int a  = foo(foo2());
}

**Comment by ratefuchs** [comment]
Probably we should prohibit function calls as function parameters (can get much more complicated in SMTLibTranslator and especially in user output after verify, too).

**Comment by ratefuchs** [comment]
Fixed in c72ca4f.
